@startuml
skinparam svgDimensionStyle false
'skinparam sequenceMessageAlign center
title 
	Example with Multiple Potential Fulfillers and Bidding
end title

hide footbox

skinparam Note<<resource>> {
    'BackgroundColor Pink
    FontName Consolas
    FontSize 14
    'FontStyle Bold
    BorderColor Black
}


actor "Patient" as Patient
participant "Provider" as Provider
participant "Facility A" as Facility_A
participant "Facility B" as Facility_B
participant "Home Nursing" as HC_Provider

==Pre-coordination==

Provider <--> HC_Provider: Register as clients, share service catalogues, share endpoints,\nand establish any administrative-subscriptions

||20||

==In Workflow==
group #eee Ordering
Patient--> Provider: Agrees following discussion with their\nprovider that skilled nursing would help with recovery
end

group Workflow

Provider -> Provider: create local order and \n**ServiceRequest**\nfor Skilled Nursing 

note left <<resource>> #lightgreen
**ServiceRequest**
|_ .id = **12345**
|_ .intent = **Order**
|_ ...

The provider may describe the patient's 
care needs in supporting info.

A provider may choose to create multiple
ServiceRequests, either for related
services or per fulfiller.
end note


note over Patient, Provider
From here, the provider may notify multiple potential fulfillers. In this example
multiple methods are used, but generally there would be one mechanism defined
for the use-case. 

end note
||10||

Provider -> Provider: create **Bid Task A**
Provider -> Facility_A: send SubscriptionStatus\nNotification to Facility A
note left <<resource>> #pink
**Bid Task A** 
|_ .id = **97531**
|_ .Status: requested
|_ .Owner: Facility **A**
|_ .Focus: ServiceRequest 12345
|_ .Code: request-fulfillment
|_ .Intent: Bid
|_ ...
end note 


||20||

Provider -> Facility_B: POST **Bid Task B**

note over Facility_B #lightblue
**Bid Task B** 
|_ .id = **86420**
|_ .Status: requested
|_ .Owner: Facility **B**
|_ .Focus: ServiceRequest 12345
|_ .Code: request-fulfillment
|_ .Intent: Bid
|_ ...
end note 

Facility_B <<-> Provider: query for ServiceRequest 12345

Provider -> HC_Provider: POST **Bid Task C**

note right <<resource>> #orange
**Bid Task C** 
|_ .id = **54321**
|_ .Status: requested
|_ .Owner: Home Care Provider
|_ .Focus: ServiceRequest 12345
|_ .Code: request-fulfillment
|_ .Intent: Bid
|_ ...
end note


HC_Provider --> HC_Provider: Evaluate request.\nDetermine no availability.

HC_Provider -> Provider: SubscriptionStatus Notification w/ Task update

note right <<resource>> #orange
**Bid Task C** 
|_ .id = **54321**
|_ .Status: **rejected**
|_ .Owner: Home Care Provider
|_ .Focus: ServiceRequest 12345
|_ .Code: request-fulfillment
|_ .Intent: Bid
|_ ...
end note


Facility_B --> Facility_B: Determine additional\ninfo needed

Facility_B -> Facility_B: Update Task.input to indicate additional information needed

Facility_B -> Provider: Send SubscriptionStatus notification

note over Facility_B #lightblue

**Bid Task B**
|_ .status = Received
|_ .businessStatus = Awaiting Info
|_ .input = value or reference to information needed,\nsuch as a Communication or Questionnaire

end note 

Provider --> Provider: review request

Provider --> Facility_B: Call to discuss

note over Facility_B #lightblue
Facility_B Agrees they could accept the patient

**Bid Task B**
|_ .status = Accepted
|_...
end note 

Facility_B -> Provider: SubscriptionStatus Notification w/ Task update

Facility_A --> Facility_A: Review request.\nSpawn Tasks in their own\nsystem. Ultimately determine\nthey could accept

Facility_A -> Provider: POST Update to\n**Bid Task A**

note right Provider #pink
**Bid Task A** 
|_ .Status: **accepted**
|_ ...
end note 


note over Provider, Facility_A
Provider now discusses with the patient.

Facility A and Facility B have both indicated they 
would take the patient.

They decide on Facility B.
end note

Provider --> Patient: discuss options

Patient --> Provider: decide Facility B fits goals best

Provider -> Provider: Records decision

Provider -> Facility_B: POST (and Create) **Coordination Task B** \n(Separate from bidding Task)

note right <<resource>> #lightblue
**Coordination Task B**
|_ .status = accepted
|_ .owner = Facility B
|_ .focus = ServiceRequest 12345
|_ .intent = order

end note
@enduml
