@startuml
'skinparam linetype ortho
skinparam linetype polyline
hide circle
hide stereotype
hide method

'skinparam defaultFontName Avenir-Book
'skinparam defaultFontSize 17
'skinparam monochrome true


'!pragma layout smetana

skinparam class<<MD>> {
 BorderColor DarkSlateGray
 BackgroundColor #DFD
 HeaderBackgroundColor #aFa
}

skinparam class<<TM>> {
 BorderColor #505090
 BackgroundColor APPLICATION
 HeaderBackgroundColor SkyBlue
}

skinparam class<<BM>> {
 BorderColor #905050
 BackgroundColor #FDD
 HeaderBackgroundColor #FAA
}

skinparam class<<RG>> {
 BorderColor #505050
 BackgroundColor #F7f7f7
 HeaderBackgroundColor #DDD
}


class "** RequestGroup 123 **" as MG <<RG>> {
* identifier: **123**
* groupIdentifier: **G01**

    }


class "** Request 1 **" as M1 <<TM>> {
* identifier: **001**
* groupIdentifier: **G01**
* intent: **option**
    }
class "** Request 2 **" as M2 <<BM>> {
* identifier: **002**
* groupIdentifier: **G01**
* intent: **option**

    }
class "** Request 3 **" as M3<<MD>> {
* identifier: **003**
* groupIdentifier: **G01**
* intent: **option**

    }


M1 -r[hidden]- M2 
M2 -r[hidden]- M3

' M2 -u[hidden]- MG


MG -d- M1
MG -d- M2
MG -d- M3

@enduml