@startuml
	'skinparam linetype polyline
	skinparam actorstyle awesome
	
	actor Placer
	actor Filler
	rectangle "**Request**" as Request
	rectangle "\t  **Task** \n(shared resource)" as Task
	rectangle "Output\n**Events**" as OutputEvents
	
	Request <-r- Task : "   makes executable  "
	Task -r-> OutputEvents : "  execution results in  "
	Placer -d-> Request: "Owns                  "
	Placer -r-> Filler: "     \t\t\t\t   "
	Filler -d-> OutputEvents: "Creates"
	Placer -d-> Task: "(usually)\ncreate and\nmay update"
	Filler -d-> Task: "accept / \n fulfill /    \n update   "

@enduml
